#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Загрузка данных своего варианта для курса «Компьютерное зрение».

Запуск из корня репозитория курса:

    python data/get_data.py --variant 7

Скрипт скачает архив variant_07.zip из релиза data-v1 на GitHub, проверит
контрольную сумму SHA-256 и распакует его в data/variant_07/. Повторный
запуск ничего не качает, если вариант уже на месте.

Из ноутбука (Jupyter, Colab, Kaggle):

    import sys; sys.path.insert(0, "data")
    from get_data import ensure_variant
    path = ensure_variant(7)          # pathlib.Path к папке варианта

Другие режимы:

    --dest DIR            куда положить папку variant_XX (по умолчанию рядом со скриптом)
    --source DIR_OR_URL   другой источник архивов: папка с variant_XX.zip или базовый URL
    --from-official       собрать вариант из официальных архивов Oxford-IIIT Pet (~810 МБ)
    --official-source X   папка или URL с images.tar.gz и annotations.tar.gz
    --force               скачать и распаковать заново
    --list                показать список вариантов
    --check               проверить уже распакованный вариант

Нужна только стандартная библиотека Python 3.8+.
"""

import argparse
import csv
import hashlib
import json
import os
import shutil
import socket
import ssl
import sys
import tarfile
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
import zipfile
import zlib
from pathlib import Path

DATASET_VERSION = "v1"
RELEASE_URL = "https://github.com/ykvnkm/computer-vision-course/releases/download/data-v1/"
OFFICIAL_URL = "https://thor.robots.ox.ac.uk/datasets/pets/"
OFFICIAL_FILES = {
    "images.tar.gz": ("67195c5e1c01f1ab5f9b6a5d22b8c27a580d896ece458917e61d459337fa318d", 791918971),
    "annotations.tar.gz": ("52425fb6de5c424942b7626b428656fcbd798db970a937df61750c0f1d358e91", 19173078),
}
STUDENT_VARIANTS = range(1, 23)   # 01..22, вариант 00 демонстрационный
MARKER = ".get_data.json"
USER_AGENT = "cv-course-get-data/1.0 (+https://github.com/ykvnkm/computer-vision-course)"

# Файлы оригинального архива, которые не попадают в варианты: это GIF под
# расширением .jpg, у них нет trimap-разметки (маска целиком «фон») и их нет
# в list.txt. Файлы *.mat из папки images/ тоже пропускаются.
EXCLUDED_STEMS = frozenset([
    "Abyssinian_34", "Egyptian_Mau_139", "Egyptian_Mau_145",
    "Egyptian_Mau_167", "Egyptian_Mau_177", "Egyptian_Mau_191",
])

# порода (как в именах файлов) -> (вид, название по-русски)
BREEDS = {
    "Abyssinian": ("cat", "абиссинская кошка"),
    "Bengal": ("cat", "бенгальская кошка"),
    "Birman": ("cat", "бирманская кошка (священная бирма)"),
    "Bombay": ("cat", "бомбейская кошка"),
    "British_Shorthair": ("cat", "британская короткошёрстная"),
    "Egyptian_Mau": ("cat", "египетская мау"),
    "Maine_Coon": ("cat", "мейн-кун"),
    "Persian": ("cat", "персидская кошка"),
    "Ragdoll": ("cat", "рэгдолл"),
    "Russian_Blue": ("cat", "русская голубая"),
    "Siamese": ("cat", "сиамская кошка"),
    "Sphynx": ("cat", "сфинкс"),
    "american_bulldog": ("dog", "американский бульдог"),
    "american_pit_bull_terrier": ("dog", "американский питбультерьер"),
    "basset_hound": ("dog", "бассет-хаунд"),
    "beagle": ("dog", "бигль"),
    "boxer": ("dog", "боксёр"),
    "chihuahua": ("dog", "чихуахуа"),
    "english_cocker_spaniel": ("dog", "английский кокер-спаниель"),
    "english_setter": ("dog", "английский сеттер"),
    "german_shorthaired": ("dog", "курцхаар (немецкая короткошёрстная легавая)"),
    "great_pyrenees": ("dog", "пиренейская горная собака"),
    "havanese": ("dog", "гаванский бишон"),
    "japanese_chin": ("dog", "японский хин"),
    "keeshond": ("dog", "кеесхонд (вольфшпиц)"),
    "leonberger": ("dog", "леонбергер"),
    "miniature_pinscher": ("dog", "цвергпинчер"),
    "newfoundland": ("dog", "ньюфаундленд"),
    "pomeranian": ("dog", "померанский шпиц"),
    "pug": ("dog", "мопс"),
    "saint_bernard": ("dog", "сенбернар"),
    "samoyed": ("dog", "самоедская собака"),
    "scottish_terrier": ("dog", "скотч-терьер"),
    "shiba_inu": ("dog", "сиба-ину"),
    "staffordshire_bull_terrier": ("dog", "стаффордширский бультерьер"),
    "wheaten_terrier": ("dog", "ирландский мягкошёрстный пшеничный терьер"),
    "yorkshire_terrier": ("dog", "йоркширский терьер"),
}
ALL_BREEDS = list(BREEDS)

# >>> GENERATED by tools/build_variants.py (не редактировать руками)
VARIANTS = {
    0: {"breeds": ["Bengal", "Egyptian_Mau", "saint_bernard", "staffordshire_bull_terrier"], "n_images": 793, "zip_size": 88909344,
        "zip_sha256": "c9a99bb74b0f327b4ef6d8cd0cc96bdcd135249195705b0efd9440e099d884ab",
        "content_sha256": "cdaeaa43dd56ca91cb43d540597818af4b5141b353757302afff547845133495"},
    1: {"breeds": ["Bengal", "Egyptian_Mau", "great_pyrenees", "havanese"], "n_images": 795, "zip_size": 83777595,
        "zip_sha256": "9e8777275f150f9aa124c6a34a85c3412faf1ad018a7064bd350a09c64732e40",
        "content_sha256": "07043cc36a0c69b63197439ab1e398857ba9f817fc6c84a50f6268dff0aea90f"},
    2: {"breeds": ["Birman", "Siamese", "basset_hound", "keeshond"], "n_images": 800, "zip_size": 93992839,
        "zip_sha256": "271a9cc8265676bf7892382f2e88b324a4d0becbb436d6c451475d393b1c054d",
        "content_sha256": "4ad545bf25494ff2f16acf5681ddf49b4155376c0b43a01b3cde87ee72d6ead6"},
    3: {"breeds": ["British_Shorthair", "Russian_Blue", "beagle", "leonberger"], "n_images": 806, "zip_size": 93504839,
        "zip_sha256": "b81b5606ac7208325f414748f571f6258b03790f0fa7f4e71bf60b92b6f7b15f",
        "content_sha256": "98f3f7b08902911c7aa901b4f772e833ebc3fe46504bc478c526962ac8e9b7df"},
    4: {"breeds": ["Birman", "Ragdoll", "german_shorthaired", "pug"], "n_images": 806, "zip_size": 84747908,
        "zip_sha256": "f5308b59ff1f6fdd8140de66d6240a92e349bab72b10fe9353b49ac4a96fb9bb",
        "content_sha256": "8dea15279050750603c9f985f10464c0c1d83d65325194f758aac4557cc065df"},
    5: {"breeds": ["British_Shorthair", "Russian_Blue", "saint_bernard", "shiba_inu"], "n_images": 805, "zip_size": 92706245,
        "zip_sha256": "81d3689eaef1d739a04260317cd49f304267c414ca5e1715c38d6a8d8b31019b",
        "content_sha256": "bcb781585ed8fa2999b345bedcb3b68b400b74c8f2cc91306ad4e6d00c6d041a"},
    6: {"breeds": ["British_Shorthair", "Russian_Blue", "german_shorthaired", "samoyed"], "n_images": 800, "zip_size": 93267054,
        "zip_sha256": "e36718a20bddc44a7b20dd82f8e106fb4e685553087c7ef3290dc97f010d5b75",
        "content_sha256": "446991610ce133bbffb27a410f70235205d1d1bca102dd95a9c7c3144cc7d704"},
    7: {"breeds": ["Birman", "Siamese", "english_setter", "pomeranian"], "n_images": 807, "zip_size": 84824767,
        "zip_sha256": "05c9c4fa6c8f6a0351a1585ae3deffaf55f2e06c32e1ff2dec8163bf1894a08e",
        "content_sha256": "a519d9e219a36a73818df2727cbc5273e21df2617a48f528ac5c1050348f9714"},
    8: {"breeds": ["Maine_Coon", "Ragdoll", "american_pit_bull_terrier", "staffordshire_bull_terrier"], "n_images": 799, "zip_size": 82319808,
        "zip_sha256": "9f435bb468c5a530c53d4a54cdc801831f7eec2041bf3eb086353d6396642db9",
        "content_sha256": "4fc77ac544a344fd716df54214319c3d5827f5686a4e639a8365d078dbf13d7d"},
    9: {"breeds": ["Persian", "Sphynx", "american_bulldog", "staffordshire_bull_terrier"], "n_images": 797, "zip_size": 91110300,
        "zip_sha256": "627b6e1c37de6d729f651fa4bd84d2cf12ee89ad419d3e23e36a799a64ccd2bf",
        "content_sha256": "da15f8b7aca582cc57cb25a27b0c1e18ba016b62d230009c66b0af4debd11fd9"},
    10: {"breeds": ["Abyssinian", "Bengal", "scottish_terrier", "wheaten_terrier"], "n_images": 798, "zip_size": 86987694,
        "zip_sha256": "c2a4fd50216ce2f595839f226909ac314d3b30c9b6b2de946f285433f15a0b05",
        "content_sha256": "568156a59a13d7618d631d09ccbd1dcb1b6f6cdf615e1042aef102c760ead0aa"},
    11: {"breeds": ["Bengal", "Egyptian_Mau", "english_cocker_spaniel", "havanese"], "n_images": 795, "zip_size": 88455979,
        "zip_sha256": "700566997bdd12dda219bdb363c94c9ac1fbfbf7ccce1eaeb380a91478f2bc5d",
        "content_sha256": "1127e28278f287c208dbc48ab09f0594735181b24991515b0814f3e0c4264e9d"},
    12: {"breeds": ["Bombay", "Egyptian_Mau", "american_pit_bull_terrier", "staffordshire_bull_terrier"], "n_images": 786, "zip_size": 71232140,
        "zip_sha256": "a63cec03058da61660af82b142dddd2a1b7a620141aa2b786a1269c253355da9",
        "content_sha256": "ebfde1f0c5a88092a0be4349b2059906f7d7d8b65dc025689a98204034edc7a4"},
    13: {"breeds": ["Maine_Coon", "Persian", "chihuahua", "miniature_pinscher"], "n_images": 806, "zip_size": 71844083,
        "zip_sha256": "94ea9653dbf969e7c459ee30da5492a6ba10c7813e202c3f2f48a8ec087ec9d6",
        "content_sha256": "01ee2dc090a27e4c2afa0f778a3c31eadaea899ff6b14f5444f7bfbbc396bff0"},
    14: {"breeds": ["British_Shorthair", "Russian_Blue", "basset_hound", "pomeranian"], "n_images": 807, "zip_size": 82392456,
        "zip_sha256": "adc39d42434901e844a4e0086cbfe97ccda25dcd0da327a36f25d8cd3a4833f0",
        "content_sha256": "2b1ba76789b6ac4dd4fa08fff259fac4c0b55717fbe6ae8b9053e548ba5c4a82"},
    15: {"breeds": ["Bombay", "Sphynx", "american_bulldog", "boxer"], "n_images": 800, "zip_size": 81099416,
        "zip_sha256": "17cacbc30783626a9b4f383180ecaa5c57ea8e295b34d0745d73c23460cddbb6",
        "content_sha256": "3cf4b6016b8103310a10c9c999799f94579f20b6e82f419986151ce4b42964ef"},
    16: {"breeds": ["Bombay", "Maine_Coon", "american_bulldog", "american_pit_bull_terrier"], "n_images": 800, "zip_size": 72934092,
        "zip_sha256": "56414a16d38f59f47c86436452b146ae11167913abe0a86bbabaee4fb2331861",
        "content_sha256": "5970c8b0dae7e4c8c80f0f3de009465e8f80977694aa4e9328abd7810c5f52f6"},
    17: {"breeds": ["Bombay", "Persian", "chihuahua", "miniature_pinscher"], "n_images": 800, "zip_size": 62574440,
        "zip_sha256": "6e07a9c705bd31d0a381721bea43f926966429b1ab565779f9cb4c7ca7a28611",
        "content_sha256": "e5d964698328e1fced2c89302a0bb371dda1d30987cf231eaf1137d9017a3f8c"},
    18: {"breeds": ["Abyssinian", "Bengal", "japanese_chin", "pug"], "n_images": 799, "zip_size": 73893622,
        "zip_sha256": "d50aa86879509d0dfea06b52bbc9fc453569e4e4ab6bdb5283d788c47b9b95ab",
        "content_sha256": "2f75278f3629e4ea0b90dd4fb483ee9ac2c30193ca807cb6f07aac2ecfaadd1e"},
    19: {"breeds": ["Birman", "Ragdoll", "great_pyrenees", "wheaten_terrier"], "n_images": 807, "zip_size": 88505118,
        "zip_sha256": "085a539b82c90e487cea192f0844ddcfc133f537ec6a5f39806ce63f8b647877",
        "content_sha256": "eb4f18e195dc440c25972f64af4ac5dce2c8fae0fe33e1cece219fdea5b12e66"},
    20: {"breeds": ["Ragdoll", "Sphynx", "american_bulldog", "boxer"], "n_images": 806, "zip_size": 88649565,
        "zip_sha256": "071e50cb70471dadaed4a20739e6ec3c9c81869f771740423935462c848d9208",
        "content_sha256": "2e782e1aef1d47e8e1d244af425c18a9439ed8ccee7b23c9af1f73c8b1793318"},
    21: {"breeds": ["Abyssinian", "Bengal", "newfoundland", "samoyed"], "n_images": 799, "zip_size": 87475688,
        "zip_sha256": "db7c5f89637c036d0362d42711f2a6c018c1fcc44dc09e822f3e39f83a75b20a",
        "content_sha256": "131b537e2334dab6a833a581d144416183404345aa90396a1556f93ac51bbd14"},
    22: {"breeds": ["Birman", "Siamese", "newfoundland", "yorkshire_terrier"], "n_images": 800, "zip_size": 92829489,
        "zip_sha256": "1708600019c4e514c312dac8c706f5bc79fae877d2a6e69c992032eea13e85cf",
        "content_sha256": "a2d817cf76a586c329d1c8b510a143ebb7f11efa22b8ed1d2eb5c9101181afc1"},
}
# <<< GENERATED


class GetDataError(RuntimeError):
    """Понятная пользователю ошибка загрузки."""


# ----------------------------------------------------------------------------
# Общая логика варианта (её же использует tools/build_variants.py)
# ----------------------------------------------------------------------------

def vname(n):
    return "variant_%02d" % int(n)


def breed_of(stem):
    return stem.rsplit("_", 1)[0]


def species_of(breed):
    return BREEDS[breed][0]


def sort_breeds(breeds):
    """Сначала кошки, потом собаки, внутри по алфавиту. Индекс = class_id."""
    return sorted(breeds, key=lambda b: (species_of(b) != "cat", b.lower()))


def natural_key(filename):
    stem = os.path.splitext(filename)[0]
    b, _, num = stem.rpartition("_")
    try:
        return (b.lower(), int(num), filename)
    except ValueError:
        return (stem.lower(), 0, filename)


def _sha256_file(path, chunk=1 << 20):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            block = f.read(chunk)
            if not block:
                break
            h.update(block)
    return h.hexdigest()


def content_digest(vdir):
    """SHA-256 от списка «путь<TAB>sha256 файла» по всем файлам варианта."""
    vdir = Path(vdir)
    lines = []
    for p in sorted(vdir.rglob("*")):
        if p.is_file() and p.name != MARKER:
            rel = p.relative_to(vdir).as_posix()
            lines.append("%s\t%s\n" % (rel, _sha256_file(str(p))))
    return hashlib.sha256("".join(lines).encode("utf-8")).hexdigest()


def write_metadata(vdir, variant, breeds, source="release"):
    """Пишет labels.csv, variant.json и README.md по содержимому папки варианта."""
    vdir = Path(vdir)
    breeds = sort_breeds(breeds)
    class_ids = dict((b, i) for i, b in enumerate(breeds))
    images = sorted((p.name for p in (vdir / "images").iterdir() if p.is_file()), key=natural_key)
    xml_stems = set(p.stem for p in (vdir / "annotations" / "xmls").glob("*.xml"))
    tri_stems = set(p.stem for p in (vdir / "annotations" / "trimaps").glob("*.png"))
    per_breed = dict((b, {"images": 0, "boxes": 0, "trimaps": 0}) for b in breeds)
    rows = []
    for fn in images:
        stem = os.path.splitext(fn)[0]
        b = breed_of(stem)
        if b not in class_ids:
            raise GetDataError("Файл %s не относится к породам варианта" % fn)
        rows.append((fn, b, species_of(b), class_ids[b]))
        per_breed[b]["images"] += 1
        per_breed[b]["boxes"] += int(stem in xml_stems)
        per_breed[b]["trimaps"] += int(stem in tri_stems)
    with open(str(vdir / "labels.csv"), "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["filename", "breed", "species", "class_id"])
        w.writerows(rows)
    info = {
        "variant": int(variant),
        "dataset_version": DATASET_VERSION,
        "source": source,
        "breeds": breeds,
        "species": dict((b, species_of(b)) for b in breeds),
        "class_ids": class_ids,
        "names_ru": dict((b, BREEDS[b][1]) for b in breeds),
        "n_images": len(rows),
        "n_boxes": sum(v["boxes"] for v in per_breed.values()),
        "n_trimaps": sum(v["trimaps"] for v in per_breed.values()),
        "per_breed": per_breed,
        "dataset": "Oxford-IIIT Pet",
        "dataset_url": "https://www.robots.ox.ac.uk/~vgg/data/pets/",
        "license": "CC BY-SA 4.0",
        "citation": "O. M. Parkhi, A. Vedaldi, A. Zisserman, C. V. Jawahar. Cats and Dogs. "
                    "IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2012.",
    }
    with open(str(vdir / "variant.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(info, f, ensure_ascii=False, indent=2)
        f.write("\n")
    with open(str(vdir / "README.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write(make_readme(info))
    return info


def make_readme(info):
    n = info["variant"]
    lines = [
        "# Вариант %02d" % n,
        "",
        "Данные курса «Компьютерное зрение», версия %s. Это часть датасета "
        "Oxford-IIIT Pet: %d изображений четырёх пород, у %d из них есть XML с боксом головы, "
        "у %d есть trimap-маска."
        % (info["dataset_version"], info["n_images"], info["n_boxes"], info["n_trimaps"]),
        "",
        "## Породы",
        "",
        "| class_id | breed (как в именах файлов) | Порода | Вид | Изображений | XML-боксов |",
        "|---:|---|---|---|---:|---:|",
    ]
    for b in info["breeds"]:
        pb = info["per_breed"][b]
        lines.append("| %d | `%s` | %s | %s | %d | %d |" % (
            info["class_ids"][b], b, info["names_ru"][b],
            "кошка" if info["species"][b] == "cat" else "собака", pb["images"], pb["boxes"]))
    lines += [
        "| | | | **Всего** | **%d** | **%d** |" % (info["n_images"], info["n_boxes"]),
        "",
        "## Что где лежит",
        "",
        "```",
        "%s/" % vname(n),
        "├── images/               изображения, исходные имена Oxford (порода_номер.jpg)",
        "├── annotations/",
        "│   ├── xmls/             Pascal VOC XML: бокс головы животного (есть не у всех изображений)",
        "│   └── trimaps/          PNG-маски: 1 = животное, 2 = фон, 3 = граница",
        "├── labels.csv            filename,breed,species,class_id",
        "├── variant.json          то же в машиночитаемом виде",
        "└── README.md             этот файл",
        "```",
        "",
        "Имя маски и XML совпадает с именем изображения: `Bengal_12.jpg` → "
        "`annotations/trimaps/Bengal_12.png` и `annotations/xmls/Bengal_12.xml`. "
        "Кошачьи породы в Oxford пишутся с заглавной буквы, собачьи со строчной.",
        "",
        "Изображения лежат в том виде, в каком их выложили авторы датасета: размеры разные, "
        "встречаются файлы в оттенках серого и с альфа-каналом.",
        "",
        "## Лицензия и ссылка",
        "",
        "Oxford-IIIT Pet Dataset распространяется по лицензии Creative Commons "
        "Attribution-ShareAlike 4.0 (CC BY-SA 4.0), авторские права на фотографии остаются "
        "у их владельцев. Этот вариант является производной работой и распространяется на тех же условиях.",
        "",
        "Авторы: Omkar M. Parkhi, Andrea Vedaldi, Andrew Zisserman, C. V. Jawahar. "
        "*Cats and Dogs.* IEEE CVPR, 2012. Страница датасета: https://www.robots.ox.ac.uk/~vgg/data/pets/",
        "",
    ]
    return "\n".join(lines)


# ----------------------------------------------------------------------------
# Вывод и окружение
# ----------------------------------------------------------------------------

def say(msg="", end="\n"):
    try:
        sys.stdout.write(msg + end)
    except UnicodeEncodeError:
        enc = sys.stdout.encoding or "ascii"
        sys.stdout.write((msg + end).encode(enc, "replace").decode(enc, "replace"))
    sys.stdout.flush()


def on_kaggle():
    return bool(os.environ.get("KAGGLE_KERNEL_RUN_TYPE")) or os.path.isdir("/kaggle/input")


def on_colab():
    return "google.colab" in sys.modules or bool(os.environ.get("COLAB_RELEASE_TAG"))


def _human(nbytes):
    return "%.1f МБ" % (nbytes / 1048576.0)


def _check_variant_number(n):
    try:
        n = int(str(n).strip())
    except (TypeError, ValueError):
        raise GetDataError("Номер варианта должен быть числом от 1 до 22, получено: %r" % (n,))
    if n not in VARIANTS:
        if not VARIANTS:
            raise GetDataError("В скрипте нет таблицы вариантов. Скачайте свежую версию get_data.py из репозитория курса.")
        raise GetDataError(
            "Варианта %d нет. Ваш вариант — это ваш порядковый номер в списке группы, "
            "число от 1 до 22." % n)
    return n


def _default_dest():
    here = Path(os.path.dirname(os.path.abspath(__file__)))
    if os.access(str(here), os.W_OK):
        return here
    return Path(os.getcwd()) / "data"


# ----------------------------------------------------------------------------
# Сеть
# ----------------------------------------------------------------------------

def _ssl_contexts():
    yield None  # системные сертификаты
    try:
        import certifi  # есть в Colab, Kaggle, Anaconda
        yield ssl.create_default_context(cafile=certifi.where())
    except Exception:
        pass
    # Последний вариант: без проверки сертификата. Это безопасно только потому,
    # что каждый скачанный файл сверяется с зашитой в скрипт суммой SHA-256.
    yield ssl._create_unverified_context()


def _is_cert_error(err):
    reason = getattr(err, "reason", err)
    return isinstance(reason, ssl.SSLError) and "CERTIFICATE" in str(reason).upper()


_CURRENT = {"variant": None}


def _network_hint(url, err):
    host = urllib.parse.urlparse(url).netloc
    msg = ["Не удалось подключиться к %s (%s)." % (host, err)]
    if on_kaggle():
        msg.append(
            "Похоже, это Kaggle с выключенным интернетом. Откройте справа панель Settings → "
            "Internet и включите его (Kaggle один раз попросит подтвердить номер телефона). "
            "Если подтвердить телефон нельзя, запустите ноутбук в Colab или локально.")
    else:
        msg.append(
            "Проверьте подключение к интернету, прокси или VPN. Если GitHub недоступен, "
            "попробуйте запасной путь: python data/get_data.py --variant %s --from-official"
            % (_CURRENT["variant"] if _CURRENT["variant"] is not None else "N"))
    return "\n".join(msg)


def _urlopen(url, headers=None, timeout=60):
    req = urllib.request.Request(url, headers=dict({"User-Agent": USER_AGENT}, **(headers or {})))
    last = None
    for ctx in _ssl_contexts():
        try:
            if ctx is None:
                return urllib.request.urlopen(req, timeout=timeout)
            return urllib.request.urlopen(req, timeout=timeout, context=ctx)
        except urllib.error.HTTPError:
            raise
        except (urllib.error.URLError, ssl.SSLError) as e:
            if _is_cert_error(e):
                last = e
                continue
            raise
    raise last


def download(url, dest_path, sha256=None, size=None, label=None, retries=4):
    """Скачивает url в dest_path с докачкой, прогрессом и проверкой SHA-256."""
    dest_path = Path(dest_path)
    part = Path(str(dest_path) + ".part")
    label = label or dest_path.name
    for attempt in range(1, retries + 1):
        have = part.stat().st_size if part.exists() else 0
        if size and have > size:
            part.unlink()
            have = 0
        headers = {"Range": "bytes=%d-" % have} if have else {}
        try:
            resp = _urlopen(url, headers=headers)
        except urllib.error.HTTPError as e:
            if e.code == 416 and have:  # уже всё скачано
                resp = None
            elif e.code == 404:
                raise GetDataError(
                    "Сервер ответил 404: файла %s нет по адресу\n  %s\n"
                    "Проверьте номер варианта. Если он верный, сообщите преподавателю: "
                    "возможно, данные ещё не опубликованы." % (label, url))
            elif attempt < retries:
                say("  Сервер ответил %d, повтор через %d с..." % (e.code, 3 * attempt))
                time.sleep(3 * attempt)
                continue
            else:
                raise GetDataError("Сервер ответил ошибкой %d при скачивании %s" % (e.code, url))
        except (urllib.error.URLError, socket.timeout, ConnectionError, OSError) as e:
            if attempt < retries and not isinstance(getattr(e, "reason", None), socket.gaierror):
                say("  Нет связи (%s), повтор через %d с..." % (getattr(e, "reason", e), 3 * attempt))
                time.sleep(3 * attempt)
                continue
            raise GetDataError(_network_hint(url, getattr(e, "reason", e)))
        if resp is not None:
            if have and getattr(resp, "status", resp.getcode()) != 206:
                have = 0  # сервер не поддержал докачку
            total = size
            if not total:
                cl = resp.headers.get("Content-Length")
                total = (int(cl) + have) if cl else None
            mode = "ab" if have else "wb"
            done = have
            t0 = time.time()
            last_print = 0.0
            try:
                with open(str(part), mode) as f:
                    while True:
                        block = resp.read(1 << 16)
                        if not block:
                            break
                        f.write(block)
                        done += len(block)
                        now = time.time()
                        if now - last_print > 0.5:
                            last_print = now
                            speed = (done - have) / max(now - t0, 1e-6)
                            if total:
                                say("\r  %s: %s из %s (%3d%%), %s/с   " % (
                                    label, _human(done), _human(total), 100 * done // total, _human(speed)), end="")
                            else:
                                say("\r  %s: %s, %s/с   " % (label, _human(done), _human(speed)), end="")
            except (socket.timeout, ConnectionError, OSError) as e:
                if attempt < retries:
                    say("\n  Связь прервалась (%s), докачиваю..." % e)
                    time.sleep(2)
                    continue
                raise GetDataError(_network_hint(url, e))
            finally:
                resp.close()
            say("\r  %s: %s, готово.%s" % (label, _human(done), " " * 30))
        if size and part.stat().st_size < size and attempt < retries:
            say("  Файл скачан не полностью, докачиваю...")
            continue
        if sha256:
            got = _sha256_file(str(part))
            if got != sha256:
                part.unlink()
                if attempt < retries:
                    say("  Контрольная сумма не совпала, качаю заново...")
                    continue
                raise GetDataError(
                    "Контрольная сумма %s не совпала (ожидалась %s, получена %s). "
                    "Файл повреждён при передаче или на сервере лежит другая версия." % (label, sha256, got))
        os.replace(str(part), str(dest_path))
        return dest_path
    raise GetDataError("Не удалось скачать %s" % url)


# ----------------------------------------------------------------------------
# Установка варианта
# ----------------------------------------------------------------------------

def _read_marker(vdir):
    try:
        with open(str(Path(vdir) / MARKER), encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def _is_installed(vdir, n):
    m = _read_marker(vdir)
    if not m or m.get("variant") != n or m.get("dataset_version") != DATASET_VERSION:
        return False
    if not (Path(vdir) / "labels.csv").is_file() or not (Path(vdir) / "images").is_dir():
        return False
    n_files = sum(1 for p in (Path(vdir) / "images").iterdir() if p.is_file())
    return n_files == m.get("n_images")


def _write_marker(vdir, n, source, zip_sha=None):
    info = _load_json(Path(vdir) / "variant.json")
    marker = {
        "variant": n, "dataset_version": DATASET_VERSION, "source": source,
        "zip_sha256": zip_sha, "n_images": info.get("n_images"),
        "content_sha256": content_digest(vdir),
        "installed_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    }
    with open(str(Path(vdir) / MARKER), "w", encoding="utf-8") as f:
        json.dump(marker, f, ensure_ascii=False, indent=2)
    return marker


def _load_json(path):
    with open(str(path), encoding="utf-8") as f:
        return json.load(f)


def _move_aside(vdir):
    i = 1
    while True:
        bak = Path("%s.old%d" % (vdir, i) if i > 1 else "%s.old" % vdir)
        if not bak.exists():
            os.replace(str(vdir), str(bak))
            say("  Старая папка %s переименована в %s" % (vdir, bak.name))
            return
        i += 1


def _free_space_check(folder, need_bytes):
    try:
        free = shutil.disk_usage(str(folder)).free
    except OSError:
        return
    if free < need_bytes:
        raise GetDataError("Мало места на диске: нужно около %s, свободно %s в %s"
                           % (_human(need_bytes), _human(free), folder))


def _extract_zip(zip_path, dest, n):
    name = vname(n)
    tmp = Path(tempfile.mkdtemp(prefix=".%s-" % name, dir=str(dest)))
    try:
        with zipfile.ZipFile(str(zip_path)) as zf:
            for info in zf.infolist():
                fn = info.filename
                if not fn.startswith(name + "/") or ".." in fn.split("/") or fn.startswith("/"):
                    raise GetDataError("В архиве посторонний путь: %s" % fn)
            zf.extractall(str(tmp))
        return tmp / name, tmp
    except zipfile.BadZipFile:
        shutil.rmtree(str(tmp), ignore_errors=True)
        raise GetDataError("Архив %s повреждён. Удалите его и запустите скрипт ещё раз." % zip_path)
    except Exception:
        shutil.rmtree(str(tmp), ignore_errors=True)
        raise


def _finalize(staged, tmp_root, final):
    if final.exists():
        _move_aside(final)
    os.replace(str(staged), str(final))
    shutil.rmtree(str(tmp_root), ignore_errors=True)


def _find_local(roots, n, max_depth=4):
    """Ищет variant_XX.zip или распакованную папку variant_XX в каталогах roots."""
    name = vname(n)
    found_dir = None
    for root in roots:
        root = os.path.abspath(str(root))
        if not os.path.isdir(root):
            continue
        base_depth = root.rstrip(os.sep).count(os.sep)
        for cur, dirs, files in os.walk(root):
            if cur.count(os.sep) - base_depth >= max_depth:
                dirs[:] = []
            if name + ".zip" in files:
                return "zip", Path(cur) / (name + ".zip")
            if found_dir is None and os.path.basename(cur) == name and "labels.csv" in files:
                found_dir = Path(cur)
            dirs.sort()
    if found_dir is not None:
        return "dir", found_dir
    return None, None


def _install_from_zip(zip_path, dest, n, spec, verify=True):
    if verify and spec.get("zip_sha256"):
        say("  Проверяю контрольную сумму %s..." % Path(zip_path).name)
        got = _sha256_file(str(zip_path))
        if got != spec["zip_sha256"]:
            raise GetDataError("Контрольная сумма %s не совпала: это не тот архив или он повреждён." % zip_path)
    _free_space_check(dest, int(spec.get("zip_size", 0) * 1.2))
    say("  Распаковываю в %s ..." % (dest / vname(n)))
    staged, tmp = _extract_zip(zip_path, dest, n)
    if spec.get("content_sha256") and content_digest(staged) != spec["content_sha256"]:
        shutil.rmtree(str(tmp), ignore_errors=True)
        raise GetDataError("Содержимое архива не совпало с ожидаемым. Скачайте вариант заново с --force.")
    _write_marker(staged, n, "release", spec.get("zip_sha256"))
    final = dest / vname(n)
    _finalize(staged, tmp, final)
    return final


def _install_from_dir(src_dir, dest, n, spec):
    say("  Копирую готовую папку %s ..." % src_dir)
    if spec.get("content_sha256") and content_digest(src_dir) != spec["content_sha256"]:
        raise GetDataError("Папка %s не совпадает с эталонным вариантом %02d (другая версия данных?)." % (src_dir, n))
    tmp = Path(tempfile.mkdtemp(prefix=".%s-" % vname(n), dir=str(dest)))
    staged = tmp / vname(n)
    shutil.copytree(str(src_dir), str(staged), ignore=shutil.ignore_patterns(MARKER))
    _write_marker(staged, n, "release", spec.get("zip_sha256"))
    final = dest / vname(n)
    _finalize(staged, tmp, final)
    return final


def ensure_variant(n, dest=None, source=None, force=False, from_official=False,
                   official_source=None, quiet=False):
    """Гарантирует, что вариант n лежит в dest/variant_NN, и возвращает путь к нему.

    n         номер варианта (1..22, 0 у преподавателя)
    dest      папка, в которой появится variant_NN (по умолчанию папка со скриптом)
    source    папка с variant_NN.zip / variant_NN или базовый URL вместо GitHub
    force     скачать и распаковать заново
    from_official  собрать вариант из официальных архивов Oxford
    """
    n = _check_variant_number(n)
    _CURRENT["variant"] = n
    spec = VARIANTS[n]
    dest = Path(dest).expanduser().resolve() if dest else _default_dest()
    dest.mkdir(parents=True, exist_ok=True)
    final = dest / vname(n)

    if not force and _is_installed(final, n):
        if not quiet:
            say("Вариант %02d уже на месте: %s" % (n, final))
        return final
    if force and final.exists():
        shutil.rmtree(str(final))

    if from_official:
        return build_from_official(n, dest, official_source)

    say("Вариант %02d: %s" % (n, ", ".join(spec["breeds"])))

    # 1. Явно указанный источник
    if source and not str(source).startswith(("http://", "https://")):
        kind, path = _find_local([source], n)
        if kind == "zip":
            return _done(_install_from_zip(path, dest, n, spec))
        if kind == "dir":
            return _done(_install_from_dir(path, dest, n, spec))
        raise GetDataError("В папке %s нет ни %s.zip, ни распакованной папки %s." % (source, vname(n), vname(n)))

    # 2. Kaggle: датасет-зеркало, подключённое к ноутбуку
    if not source and on_kaggle():
        kind, path = _find_local(["/kaggle/input"], n, max_depth=5)
        if kind == "zip":
            say("  Нашёл архив в подключённых данных Kaggle: %s" % path)
            return _done(_install_from_zip(path, dest, n, spec))
        if kind == "dir":
            say("  Нашёл вариант в подключённых данных Kaggle: %s" % path)
            return _done(_install_from_dir(path, dest, n, spec))

    # 3. Скачивание (GitHub Releases или указанный URL)
    base = str(source) if source else RELEASE_URL
    if not base.endswith("/"):
        base += "/"
    url = base + vname(n) + ".zip"
    _free_space_check(dest, int(spec.get("zip_size", 0) * 2.3))
    zip_path = dest / (vname(n) + ".zip")
    if zip_path.exists() and spec.get("zip_sha256") and _sha256_file(str(zip_path)) == spec["zip_sha256"]:
        say("  Архив уже скачан: %s" % zip_path)
    else:
        say("  Скачиваю %s" % url)
        download(url, zip_path, spec.get("zip_sha256"), spec.get("zip_size"), label=zip_path.name)
    final = _install_from_zip(zip_path, dest, n, spec, verify=False)
    try:
        zip_path.unlink()
    except OSError:
        pass
    return _done(final)


def _done(final):
    say("Готово: %s (%d изображений)" % (final, _load_json(final / "variant.json")["n_images"]))
    return final


load_variant = ensure_variant  # синоним


# ----------------------------------------------------------------------------
# Запасной путь: сборка из официальных архивов Oxford-IIIT Pet
# ----------------------------------------------------------------------------

def _official_archives(dest, official_source):
    src = official_source or OFFICIAL_URL
    paths = {}
    if not str(src).startswith(("http://", "https://")):
        for name in OFFICIAL_FILES:
            p = Path(src).expanduser() / name
            if not p.is_file():
                raise GetDataError("В папке %s нет файла %s" % (src, name))
            paths[name] = p
        return paths
    cache = dest / ".oxford-pets-cache"
    cache.mkdir(parents=True, exist_ok=True)
    need = sum(s for _, s in OFFICIAL_FILES.values())
    _free_space_check(cache, int(need * 1.3))
    if not str(src).endswith("/"):
        src = str(src) + "/"
    for name, (sha, size) in OFFICIAL_FILES.items():
        p = cache / name
        if p.exists() and p.stat().st_size == size and _sha256_file(str(p)) == sha:
            say("  %s уже скачан" % name)
        else:
            say("  Скачиваю %s%s (%s)" % (src, name, _human(size)))
            download(src + name, p, sha, size, label=name)
        paths[name] = p
    return paths


def build_from_official(n, dest, official_source=None):
    n = _check_variant_number(n)
    spec = VARIANTS[n]
    breeds = set(spec["breeds"])
    dest = Path(dest)
    say("Вариант %02d: сборка из официальных архивов Oxford-IIIT Pet" % n)
    arch = _official_archives(dest, official_source)
    tmp = Path(tempfile.mkdtemp(prefix=".%s-" % vname(n), dir=str(dest)))
    staged = tmp / vname(n)
    for sub in ("images", "annotations/xmls", "annotations/trimaps"):
        (staged / sub).mkdir(parents=True)

    def wanted(stem):
        return breed_of(stem) in breeds and stem not in EXCLUDED_STEMS

    try:
        stems = set()
        say("  Извлекаю изображения...")
        with tarfile.open(str(arch["images.tar.gz"]), "r|gz") as tf:
            for m in tf:
                base = m.name.rsplit("/", 1)[-1]
                if not m.isfile() or base.startswith("._") or not base.endswith(".jpg"):
                    continue
                stem = base[:-4]
                if wanted(stem):
                    with open(str(staged / "images" / base), "wb") as out:
                        shutil.copyfileobj(tf.extractfile(m), out)
                    stems.add(stem)
        say("  Извлекаю разметку...")
        with tarfile.open(str(arch["annotations.tar.gz"]), "r|gz") as tf:
            for m in tf:
                parts = m.name.split("/")
                base = parts[-1]
                if not m.isfile() or base.startswith("._") or len(parts) < 2:
                    continue
                if parts[-2] == "trimaps" and base.endswith(".png") and base[:-4] in stems:
                    target = staged / "annotations" / "trimaps" / base
                elif parts[-2] == "xmls" and base.endswith(".xml") and base[:-4] in stems:
                    target = staged / "annotations" / "xmls" / base
                else:
                    continue
                with open(str(target), "wb") as out:
                    shutil.copyfileobj(tf.extractfile(m), out)
        if not stems:
            raise GetDataError("В архиве изображений не нашлось файлов нужных пород.")
        write_metadata(staged, n, spec["breeds"], source="official")
        _write_marker(staged, n, "official")
        final = dest / vname(n)
        _finalize(staged, tmp, final)
    except (tarfile.TarError, EOFError, zlib.error) as e:
        shutil.rmtree(str(tmp), ignore_errors=True)
        raise GetDataError("Официальный архив повреждён (%s). Удалите папку .oxford-pets-cache и повторите." % e)
    except Exception:
        shutil.rmtree(str(tmp), ignore_errors=True)
        raise
    say("Готово: %s (%d изображений)" % (final, len(stems)))
    say("Вариант собран из официального архива Oxford. Состав может немного отличаться от архива курса.\n"
        "Когда основной источник станет доступен, скачайте вариант заново:\n"
        "  python data/get_data.py --variant %d --force" % n)
    return final


# ----------------------------------------------------------------------------
# Командная строка
# ----------------------------------------------------------------------------

def _print_list():
    say("Вариант  Породы")
    for n in sorted(VARIANTS):
        tag = "  (демонстрационный)" if n == 0 else ""
        say("  %02d     %s%s" % (n, ", ".join(VARIANTS[n]["breeds"]), tag))


def _check(n, dest):
    n = _check_variant_number(n)
    dest = Path(dest).expanduser().resolve() if dest else _default_dest()
    vdir = dest / vname(n)
    if not vdir.is_dir():
        raise GetDataError("Папки %s нет. Сначала скачайте вариант." % vdir)
    m = _read_marker(vdir) or {}
    got = content_digest(vdir)
    ref = VARIANTS[n].get("content_sha256")
    if m.get("source") == "official":
        say("Вариант собран из официального архива; сравнение с эталоном не проводится.")
        return
    if got == ref:
        say("Вариант %02d в порядке: %s" % (n, vdir))
    else:
        raise GetDataError("Файлы в %s отличаются от эталона. Перекачайте: --force" % vdir)


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Скачивает данные варианта курса «Компьютерное зрение» (Oxford-IIIT Pet).")
    ap.add_argument("--variant", "-v", help="номер варианта, 1..22")
    ap.add_argument("--dest", help="папка, где появится variant_NN (по умолчанию data/)")
    ap.add_argument("--source", help="папка с variant_NN.zip или базовый URL вместо GitHub")
    ap.add_argument("--from-official", action="store_true",
                    help="собрать вариант из официальных архивов Oxford (~810 МБ)")
    ap.add_argument("--official-source", help="папка или URL с images.tar.gz и annotations.tar.gz")
    ap.add_argument("--force", action="store_true", help="скачать и распаковать заново")
    ap.add_argument("--list", action="store_true", help="показать список вариантов")
    ap.add_argument("--check", action="store_true", help="проверить распакованный вариант")
    args = ap.parse_args(argv)
    try:
        if args.list:
            _print_list()
            return 0
        if args.variant is None:
            ap.print_usage()
            say("Укажите номер варианта, например: python data/get_data.py --variant 7")
            return 2
        if args.check:
            _check(args.variant, args.dest)
            return 0
        ensure_variant(args.variant, dest=args.dest, source=args.source, force=args.force,
                       from_official=args.from_official, official_source=args.official_source)
        return 0
    except GetDataError as e:
        say("\nОШИБКА: %s" % e)
        return 1
    except KeyboardInterrupt:
        say("\nПрервано. Запустите команду ещё раз: скачивание продолжится с того же места.")
        return 130


if __name__ == "__main__":
    sys.exit(main())
